/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Iran
 */
public class EscalaProvaMain extends javax.swing.JFrame {
public static int NDias=0, NFiscais=0;
public static String NomeEscala;
public static int Status = 0;


    /**
     * Creates new form EscalaProva
     */
    public EscalaProvaMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemNovaEscala = new javax.swing.JMenuItem();
        jMenuItemSalvar = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Escala de Prova");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/Sair.PNG"))); // NOI18N
        jButton3.setToolTipText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Arquivo");

        jMenuItemAbrir.setText("Abrir");
        jMenu1.add(jMenuItemAbrir);

        jMenuItemNovaEscala.setText("Nova Escala");
        jMenuItemNovaEscala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNovaEscalaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemNovaEscala);

        jMenuItemSalvar.setText("Salvar");
        jMenuItemSalvar.setToolTipText("");
        jMenuItemSalvar.setEnabled(false);
        jMenu1.add(jMenuItemSalvar);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(653, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(707, 432));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItemNovaEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNovaEscalaActionPerformed

// ************** Abrir Janela para criar nova Escala de professores **************************
 CriarEscala();

 if (Status==1){
     Status = 0;// para pegar o retorno dos DiasSalas()
        DiasSalas();
 }
 
 
  if (Status==1){
     Status = 0;// para pegar o retorno dos Nprofessores()
        Nprofessores();
 }
  
   if (Status==1){
     Status = 0;// para pegar o retorno dos Nprofessores()
        TabelaProfessores();
 }
  
  
  
  
 
    }//GEN-LAST:event_jMenuItemNovaEscalaActionPerformed
public static void Nprofessores(){
      JDialogFiscal  dlProfe= new JDialogFiscal(null, true);
      
      dlProfe.setVisible(true);
      // ************* PEGAR O A QUANTIDADE DE FISCAIS *****************
   
     NFiscais =dlProfe.Infor_NFiscias();
             Status = dlProfe.Status();
           System.out.println("141 principal NFiscais =  "+NFiscais);
 // ************* FIM DE PEGAR A QUANTIDADE DE FISCAIS *****************     
        
}
    
 public static void  TabelaProfessores(){
      DialogTabelaProfessor  dlTabelaProfe= new DialogTabelaProfessor(null, true);
      
      dlTabelaProfe.Receber_NFisc_NDias_Nome(NFiscais, NDias, NomeEscala);
      
      dlTabelaProfe.setVisible(true);
     
     
     
 }   
 
    public static void DiasSalas(){
          JDialogTabelaDias_Salas  dlDias_Salas= new JDialogTabelaDias_Salas(null, true);
          
           // ************* ENVIA O NOME E A QUANTIDADE DE DIAS *****************
   
     
       dlDias_Salas.Receber_Nome_NDias(NDias, NomeEscala);
 // ************* FIM DE ENVIAR O NOME E A QUANTIDADE DE DIAS *****************
            dlDias_Salas.setVisible(true); 
        
       Status = dlDias_Salas.Status();
            
            
            
    }
    
    
     public static void CriarEscala(){
          DialogCriarEscala  dlgCriar= new DialogCriarEscala(null, true);
           
          dlgCriar.setVisible(true); 
         
   // ************* PEGAR O NOME E A QUANTIDADE DE DIAS *****************
   
     
     NDias =dlgCriar.Infor_NDias();
   NomeEscala=dlgCriar.Infor_NomeEscala();
          Status = dlgCriar.Status();
           System.out.println("161 principal NDias =  "+NDias);
 // ************* FIM DE PEGAR O NOME E A QUANTIDADE DE DIAS *****************
  
  
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscalaProvaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscalaProvaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscalaProvaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscalaProvaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscalaProvaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemNovaEscala;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSalvar;
    // End of variables declaration//GEN-END:variables
}
