
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Iran
 */
public class JDialogTabelaDias_Salas extends javax.swing.JDialog {
        int StatusDados=0;
        String NomeEscala;   
        int NDias=0; 
        int []diaseSalas ;
        
        
        
    /**
     * Creates new form JDialogDias_Salas
     */
    public JDialogTabelaDias_Salas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDias_Turmas = new javax.swing.JTable();
        jButtonContinuar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextNomedaEscala = new javax.swing.JTextField();
        jTextnDias = new javax.swing.JTextField();
        jLabelNDias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DIAS E SALAS");

        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dias, Salas e Reservas"));

        jTableDias_Turmas.setAutoCreateRowSorter(true);
        jTableDias_Turmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "A", "B"
            }
        ));
        jTableDias_Turmas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableDias_Turmas.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jScrollPane2.setViewportView(jTableDias_Turmas);

        jButtonContinuar.setText("CONTINUAR");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome da Escala");

        jTextNomedaEscala.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNomedaEscala.setToolTipText("");

        jTextnDias.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextnDias.setToolTipText("");

        jLabelNDias.setText("Número de dias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextNomedaEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNDias, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextnDias, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonContinuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextNomedaEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextnDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNDias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonContinuar))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jScrollPane2.getAccessibleContext().setAccessibleName("Dias, Salas e Reservas");

        setSize(new java.awt.Dimension(508, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        StatusDados= 0;
        dispose();

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public void MontarTabela(){
        
        //***************** MONTAR TABELA ***************************      
//int ndias = 3;// receber este valor do jdialog anterior
jTextNomedaEscala.setText(NomeEscala);
jTextnDias.setText(String.valueOf(NDias));
System.out.println("120 na janela 3 NDias =  "+NDias);
            DefaultTableModel modeloturmas = (DefaultTableModel) jTableDias_Turmas.getModel();
            modeloturmas.setColumnCount(0);
// ****** CRIA AS COLUNAS *****************************            

               modeloturmas.addColumn("Dia", new Object [] {""});
               modeloturmas.addColumn("HORÁRIO", new Object [] {""});
               modeloturmas.addColumn("SALAS", new Object [] {""});
//               modeloturmas.addColumn("N Reservas", new Object [] {""});

// ******  FIM DE CRIAR AS COLUNAS *****************************     
modeloturmas.setNumRows(0);
int lin1=-2;
int lin2=-1;
// ****** CRIA AS LINHAS COM VALORES PADRÕES *****************************            

for (int i = 1; i<=NDias ;i++){//cria as linhas = turmas2*
            modeloturmas.addRow(new Object [] { ""} );
 lin1=lin1+2;
lin2=lin2+2;
 modeloturmas.setValueAt(i, lin1, 0);
     modeloturmas.setValueAt("1h", lin1, 1); 
       modeloturmas.setValueAt("1", lin1, 2);
//              modeloturmas.setValueAt("1", lin1, 3);
                modeloturmas.addRow(new Object [] { ""} );
                modeloturmas.setValueAt(i, lin2, 0);
                modeloturmas.setValueAt("2h", lin2, 1);
                modeloturmas.setValueAt("1", lin2, 2);
//                modeloturmas.setValueAt("1", lin2, 3);
                
        }
// ******  FIM DE CRIAR AS LINHAS COM VALORES PADRÕES *****************************
jTableDias_Turmas.getColumnModel().getColumn(0).setPreferredWidth(40);
         jTableDias_Turmas.getColumnModel().getColumn(1).setPreferredWidth(80);
         jTableDias_Turmas.getColumnModel().getColumn(2).setPreferredWidth(80);
//         jTableDias_Turmas.getColumnModel().getColumn(3).setPreferredWidth(120);
                     
 
DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        
        jTableDias_Turmas.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTableDias_Turmas.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
         jTableDias_Turmas.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
//        jTableDias_Turmas.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
//***************** FIM DE MONTAR TABELA ***************************      

        
    }
    
   public void Receber_Nome_NDias(int NDiasinput, String NomeEscalaimput){
     
       NomeEscala=NomeEscalaimput;   
       NDias=   NDiasinput;
//   System.out.println("168 janela 3 NDias =  "+NDias);
        MontarTabela();
        
   } 
    
    
    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        ///LER TODOS OS DADOS E CONTINUAR SE TUDO ESTIVER CERTO

        ler_dados();

//        if (gravar == 1){
//            //            //Salva os dados e sai
//            //            gravar_dados();
//
//            //ENVIAR VALORES
//            //    Horario_Escala fprincipal = new Horario_Escala();
//            // //ou assim JFrameCriar_Escala dlgtemp= new JFrameCriar_Escala(this, true);//mas não sei a diferença ainda
            StatusDados= 1;
//
//            //
//            //Horario_Escala main= new Horario_Escala(NomeEscala,Nundaescala, Status );
//            //
//            //        main.Receber_dados_Criados(ndias,nprof);//,nmaxreserva,nmaxfiscal);
//        //        main.setVisible(true);
//        //                     Status= 1;
        dispose();
//
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    
    
     public int Status(){
        
     return StatusDados;
             
    }
     
     public int[] matriz(){
         
         return diaseSalas;
         
     }
     
     
     public void ler_dados(){
      DefaultTableModel DadosTabelaDias = (DefaultTableModel) jTableDias_Turmas.getModel();
      diaseSalas = new int [2*NDias];//o comprimento sera o numero de dias  
//      int totalsalas=0;
      for (int lin = 1; lin<=2*NDias ;lin++){ 
//          totalsalas = totalsalas+Integer.parseInt((String)jTableDias_Turmas.getValueAt(lin-1,2));
      diaseSalas [lin-1] = Integer.parseInt((String)jTableDias_Turmas.getValueAt(lin-1,2));  
//      System.out.println("tabela dias 268 diaseSalas = "+diaseSalas [lin-1]);
      } 
      
//       System.out.println("271 tabela totalsalas = "+totalsalas);
      
      
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaDias_Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaDias_Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaDias_Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaDias_Salas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogTabelaDias_Salas dialog = new JDialogTabelaDias_Salas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNDias;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDias_Turmas;
    private javax.swing.JTextField jTextNomedaEscala;
    private javax.swing.JTextField jTextnDias;
    // End of variables declaration//GEN-END:variables
}
